# Generated by Django 4.1.5 on 2023-02-27 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
